### PR TITLE
place cursor before a period instead of any non-alphanumeric character

### PR DESCRIPTION
**Pull request by CogentRedTester**
Fixes a small uncommon bug in #1

### CODE REVIEW

**Comment by CogentRedTester** [comment]
Sorry about that, should have caught it before the PR

**Comment by CogentRedTester** [comment]
Please let me know if something doesn't work after updating user-input and user-input-module

**Comment by Kayizoku** [comment]
No problem, I appreciate these updates to improve the script.

So far, things are working as they should too.

**Comment by Kayizoku** [comment]
This is not in regards to this script but something I am creating. I have tried asking in the community but no one is helpful, so if it's no trouble, I would like your help. I am writing a script to log video per line. But it's not writing to any .txt file and my log does not read any errors. I was wondering if you could help me figure out why that's happening. I would deeply appreciate the help. Only the osd_message kicks in but for some reason file:write is not working. If you need the whole code, just tell me, but for now, I think the issue lies in this snippet.

Here's a visual representation of what I am trying to do:

Breaking_Bad.Episode1.mkv

Breaking_Bad.Episode2.mkv

.

.

.

-- write to file when exiting the player or switching file
        function on_file_end()
            local message = totaltime .. "s, " .. timeloaded .. filename .. "\n"
            local file = io.open(logpath, "a")
            local lines = {}
            if not paused then totaltime = totaltime + os.clock() - lasttime end
            if file_exists(logpath) then
            for l in file:lines() do
                if not l:find(message "%a", 1, true) then
                lines[#lines+1] = l
                file:write(message)
                file:close()
                mp.osd_message("test")
            end
        end  
    end
end

**Pull request merged**
